import type { Task } from '../types';
import { enrichTask } from '../utils/priority';

const now = new Date();
const d = (days: number) => new Date(now.getTime() + days * 86400000).toISOString();

const rawTasks = [
  {
    id: '1',
    title: 'Finalize Q3 investor deck',
    description: 'Update slides with latest metrics, revenue projections, and team growth.',
    due: d(1),
    importance: 10,
    urgency: 9,
    effortHours: 3,
    status: 'in-progress' as const,
    category: 'work' as const,
    tags: ['investor', 'finance'],
    createdAt: d(-3),
  },
  {
    id: '2',
    title: 'Fix auth bug in production',
    description: 'Users are being logged out randomly. Investigate JWT expiry logic.',
    due: d(0),
    importance: 9,
    urgency: 10,
    effortHours: 2,
    status: 'todo' as const,
    category: 'work' as const,
    tags: ['bug', 'auth'],
    createdAt: d(-1),
  },
  {
    id: '3',
    title: 'Weekly team retrospective',
    description: 'Gather feedback, set improvement goals, celebrate wins.',
    due: d(2),
    importance: 7,
    urgency: 6,
    effortHours: 1,
    status: 'todo' as const,
    category: 'work' as const,
    tags: ['meeting'],
    createdAt: d(-2),
  },
  {
    id: '4',
    title: 'Read "Deep Work" chapters 3–5',
    description: 'Focus on deep work strategies and daily routines.',
    due: d(5),
    importance: 6,
    urgency: 3,
    effortHours: 2,
    status: 'todo' as const,
    category: 'learning' as const,
    tags: ['reading', 'productivity'],
    createdAt: d(-4),
  },
  {
    id: '5',
    title: 'Morning run 5km',
    description: 'Maintain cardio baseline. Aim for sub-30min.',
    due: d(0),
    importance: 7,
    urgency: 5,
    effortHours: 0.5,
    status: 'done' as const,
    category: 'health' as const,
    tags: ['exercise'],
    createdAt: d(-1),
  },
  {
    id: '6',
    title: 'Update landing page copy',
    description: 'Revise headline and CTA based on A/B test results.',
    due: d(4),
    importance: 7,
    urgency: 5,
    effortHours: 2,
    status: 'todo' as const,
    category: 'work' as const,
    tags: ['marketing'],
    createdAt: d(-2),
  },
  {
    id: '7',
    title: 'Call dentist for appointment',
    description: 'Schedule overdue cleaning.',
    due: d(7),
    importance: 5,
    urgency: 4,
    effortHours: 0.25,
    status: 'todo' as const,
    category: 'personal' as const,
    tags: ['health'],
    createdAt: d(-5),
  },
  {
    id: '8',
    title: 'Write technical spec for API v2',
    description: 'Document new endpoints, auth changes, and rate limiting.',
    due: d(6),
    importance: 8,
    urgency: 6,
    effortHours: 4,
    status: 'in-progress' as const,
    category: 'work' as const,
    tags: ['api', 'docs'],
    createdAt: d(-2),
  },
];

export const mockTasks: Task[] = rawTasks.map(enrichTask);
